---
require:
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/LineLength:
  Max: 120
Naming/FileName:
  Enabled: false
