---
name: RSpec Ruby

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: install bundler and gems
        run: |
          gem install bundler
          bundle install --jobs 3 --retry 3

      - name: run RSpec
        run: |
          bundle exec rspec
